### ISSUE TITLE
sorting in gridfield does not take translation into account

### ISSUE THREAD

**Issue by sunnysideup** [tractorcow/silverstripe-fluent#447]
SS4.1 (CWP)

We have a DataObject that is translated.

When viewing it in the ModelAdmin and sorting it by the "translatable" Title of the object, it always uses the English term to sort even though in the other language the word should be in a different position (due to it starting with T instead of A). 

How to replicate:

1. add Fluent to a dataobject

2. show dataobject in ModelAdmin

3. translate Title into two languages for one of these DataObjects

4. sort ModelAdmin by Title in Language 1

5. switch Language using the Fluent Dropdown
![image](https://user-images.githubusercontent.com/167154/43295914-409149e0-919c-11e8-8e9d-339bc6087c6c.png)

6. sort dataObject again by Title 

7. Now note that the translated version is in the wrong spot in the sorted list.

**Comment by robbieaverill** [comment]
We have fixed this already in fluent 4.1.x, but it wasn’t included in CWP 2.1.0. We need to iron out a couple of bugs, but would appreciate your feedback if you decide to pull the latest branch in to test it out! I’m going to close for now.

**Comment by sunnysideup** [comment]
Thank you Robbie.  

We have already upgraded to fluent 4.1.3 - but we are still experiencing this issue.

**Comment by robbieaverill** [comment]
@sunnysideup sorry, I posted that from my phone so didn't have an issue to reference handy.

The duplicate issue is #208 and we fixed it with #415. These changes are in the 4.1 branch, but haven't been released yet. In order to pull them into CWP 2.1 you'd need to add an inline alias for fluent:

```
"require": {
    "tractorcow/silverstripe-fluent": "4.1.x-dev as 4.1.3"
}
```

**Comment by sunnysideup** [comment]
Thank you.
